# Generated by Django 4.1 on 2024-08-02 14:04

from django.db import migrations, models

def my_function(apps, schema_editor):
    # logic will go here
    snippets = []
    Snippet = apps.get_model("apphealth", "Snippet")
    #business = Business(camis=row[0], name=row[1],
    #                            address="{} {} {} {}".format(row[3], row[4], row[2], row[5]),
    #                            phone=row[6], cuisine_description=row[7])
    snippets.append(Snippet(
        title="sample",
        code="Test code"

    ))
    Snippet.objects.bulk_create(snippets)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RunPython(my_function),

    ]
