# Generated by Django 4.1 on 2024-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
