# Generated by Django 4.1 on 2024-08-05 02:44

from django.db import migrations, models
from ....helper.raw_data import get_raw_json

def my_migration(apps, schema_editor):
    # logic will go here
    snippets = []
    Movie = apps.get_model("appmovie", "Movie")
    Poster = apps.get_model("appmovie", "Poster")

    rows_fmovies =  get_raw_json("fmovies24-to-datadump")
    for row in rows_fmovies:
        #tbl_fmovie_poster = []
        for item in row['result']['items']:
            #print(item,":")
            tbl_poster = []
            ins_movie = Movie(title = item['extracted_item']['label'], url=item['source']['url'],type=item['extracted_item']['type'],source="fmovies")
            ins_movie.save()
            ins_movie_id = ins_movie.id

            for poster in item['extracted_item']['posters']:
                tbl_poster.append(Poster(
                    movie_id = ins_movie_id,
                    url = poster['source']['url'],
                    type = poster['type']
                ))
            Poster.objects.bulk_create(tbl_poster)
    rows_gogoflix =  get_raw_json("gogoflix-shop-datadump")
    for row in rows_gogoflix:
        for item in row['result']['items']:
            #print(item,":")
            tbl_poster = []
            ins_movie = Movie(title = item['extracted_item']['label'], url=item['source']['url'],type=item['extracted_item']['type'],source="gogoflix")
            ins_movie.save()
            ins_movie_id = ins_movie.id

            for poster in item['extracted_item']['posters']:
                tbl_poster.append(Poster(
                    movie_id = ins_movie_id,
                    url = poster['source']['url'],
                    type = poster['type']
                ))
            Poster.objects.bulk_create(tbl_poster)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.IntegerField()),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.CharField(blank=True, default='', max_length=200)),

            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RunPython(my_migration),
    ]
